//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATG_Notifier.Desktop.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class AppState : global::System.Configuration.ApplicationSettingsBase {
        
        private static AppState defaultInstance = ((AppState)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AppState())));
        
        public static AppState Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentChapterId {
            get {
                return ((string)(this["CurrentChapterId"]));
            }
            set {
                this["CurrentChapterId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WasUpdateServiceRunning {
            get {
                return ((bool)(this["WasUpdateServiceRunning"]));
            }
            set {
                this["WasUpdateServiceRunning"] = value;
            }
        }
    }
}
