//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATG_Notifier.Desktop.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class AppStateMostRecentChapterInfo : global::System.Configuration.ApplicationSettingsBase {
        
        private static AppStateMostRecentChapterInfo defaultInstance = ((AppStateMostRecentChapterInfo)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AppStateMostRecentChapterInfo())));
        
        public static AppStateMostRecentChapterInfo Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NumberAndTitle {
            get {
                return ((string)(this["NumberAndTitle"]));
            }
            set {
                this["NumberAndTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WordCount {
            get {
                return ((int)(this["WordCount"]));
            }
            set {
                this["WordCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReleaseTime {
            get {
                return ((string)(this["ReleaseTime"]));
            }
            set {
                this["ReleaseTime"] = value;
            }
        }
    }
}
